apiVersion: batch/v1
kind: Job
metadata:
  name: feynman-job
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: feynman
    spec:
      restartPolicy: Never
      containers:
        - name: feynman
          image: feynman:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /data
          args:
            - "-c"
            - "/data/generated/circuits/qft/qft_n8_k2.qasm"
            - "-i"
            - "/data/generated/statevectors/ket0_size1.hsv"
            - "-b"
            - "/data/generated/hexstring_sets/nrhex10_size1_from0x0_to0xA.hs"
            - "-o"
            - "/data/outputs/tmp/qft_n8_k2_run_job.hsv"
            - "-t"
            - "0.0"
            - "-v"
            - "1"
      volumes:
        - name: data
          hostPath:
            path: /data
            type: Directory
